export const JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET';
export const JWT_ACCESS_EXPIRES_IN = 'JWT_ACCESS_EXPIRES_IN';
export const JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';
export const JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN';
